all:
	g++ -std=c++11 -Wall main.cpp -g -o main && ./main
ostra:
	g++ -std=c++11 -Wall ostra.cpp -g -o ostra && ./ostra && rm ostra
proc:
	g++ -std=c++11 -Wall procriar.cpp -g -o proc && ./proc && rm proc
it:
	g++ -std=c++11 -Wall iterador.cpp -g -o it && ./it && rm it