all:
	g++ -Wall main.cpp -o main
	./main
cinema:
	g++ -Wall cinema.cpp -o cinema
	./cinema
bidimensional:
	g++ -Wall bidimensional.cpp -o bidimensional
	./bidimensional
cinemaPonteiros:
	g++ -Wall cinemaPonteiros.cpp -o cinemaPonteiros
	./cinemaPonteiros