all:
	g++ -std=c++11 -Wall calculadora.cpp -g -o calculadora
	./calculadora
segredo:
	g++ -std=c++11 -Wall segredo.cpp -g -o segredo
	./segredo
	rm segredo
agiota:
	g++ -Wall -std=c++11 agiota.cpp -g -o agiota
	./agiota
	rm agiota